// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protocols/protobuf/sample.proto

#ifndef PROTOBUF_src_2fprotocols_2fprotobuf_2fsample_2eproto__INCLUDED
#define PROTOBUF_src_2fprotocols_2fprotobuf_2fsample_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_src_2fprotocols_2fprotobuf_2fsample_2eproto();
void protobuf_AssignDesc_src_2fprotocols_2fprotobuf_2fsample_2eproto();
void protobuf_ShutdownFile_src_2fprotocols_2fprotobuf_2fsample_2eproto();

class Msg;

// ===================================================================

class Msg : public ::google::protobuf::Message {
 public:
  Msg();
  virtual ~Msg();

  Msg(const Msg& from);

  inline Msg& operator=(const Msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg& default_instance();

  void Swap(Msg* other);

  // implements Message ----------------------------------------------

  Msg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg& from);
  void MergeFrom(const Msg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 userId = 1;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 userid() const;
  inline void set_userid(::google::protobuf::uint32 value);

  // required string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // repeated uint32 creatTime = 5;
  inline int creattime_size() const;
  inline void clear_creattime();
  static const int kCreatTimeFieldNumber = 5;
  inline ::google::protobuf::uint32 creattime(int index) const;
  inline void set_creattime(int index, ::google::protobuf::uint32 value);
  inline void add_creattime(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      creattime() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_creattime();

  // @@protoc_insertion_point(class_scope:Test.Msg)
 private:
  inline void set_has_userid();
  inline void clear_has_userid();
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > creattime_;
  ::google::protobuf::uint32 userid_;
  friend void  protobuf_AddDesc_src_2fprotocols_2fprotobuf_2fsample_2eproto();
  friend void protobuf_AssignDesc_src_2fprotocols_2fprotobuf_2fsample_2eproto();
  friend void protobuf_ShutdownFile_src_2fprotocols_2fprotobuf_2fsample_2eproto();

  void InitAsDefaultInstance();
  static Msg* default_instance_;
};
// ===================================================================


// ===================================================================

// Msg

// required uint32 userId = 1;
inline bool Msg::has_userid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Msg::set_has_userid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Msg::clear_has_userid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Msg::clear_userid() {
  userid_ = 0u;
  clear_has_userid();
}
inline ::google::protobuf::uint32 Msg::userid() const {
  // @@protoc_insertion_point(field_get:Test.Msg.userId)
  return userid_;
}
inline void Msg::set_userid(::google::protobuf::uint32 value) {
  set_has_userid();
  userid_ = value;
  // @@protoc_insertion_point(field_set:Test.Msg.userId)
}

// required string name = 3;
inline bool Msg::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Msg::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Msg::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Msg::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Msg::name() const {
  // @@protoc_insertion_point(field_get:Test.Msg.name)
  return *name_;
}
inline void Msg::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:Test.Msg.name)
}
inline void Msg::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:Test.Msg.name)
}
inline void Msg::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:Test.Msg.name)
}
inline ::std::string* Msg::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:Test.Msg.name)
  return name_;
}
inline ::std::string* Msg::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Msg::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:Test.Msg.name)
}

// repeated uint32 creatTime = 5;
inline int Msg::creattime_size() const {
  return creattime_.size();
}
inline void Msg::clear_creattime() {
  creattime_.Clear();
}
inline ::google::protobuf::uint32 Msg::creattime(int index) const {
  // @@protoc_insertion_point(field_get:Test.Msg.creatTime)
  return creattime_.Get(index);
}
inline void Msg::set_creattime(int index, ::google::protobuf::uint32 value) {
  creattime_.Set(index, value);
  // @@protoc_insertion_point(field_set:Test.Msg.creatTime)
}
inline void Msg::add_creattime(::google::protobuf::uint32 value) {
  creattime_.Add(value);
  // @@protoc_insertion_point(field_add:Test.Msg.creatTime)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
Msg::creattime() const {
  // @@protoc_insertion_point(field_list:Test.Msg.creatTime)
  return creattime_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
Msg::mutable_creattime() {
  // @@protoc_insertion_point(field_mutable_list:Test.Msg.creatTime)
  return &creattime_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Test

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_src_2fprotocols_2fprotobuf_2fsample_2eproto__INCLUDED
