/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sample_proto_constants.h"

namespace app {

const sample_protoConstants g_sample_proto_constants;

sample_protoConstants::sample_protoConstants() {
}

} // namespace

