/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sample_proto_CONSTANTS_H
#define sample_proto_CONSTANTS_H

#include "sample_proto_types.h"

namespace app {

class sample_protoConstants {
 public:
  sample_protoConstants();

};

extern const sample_protoConstants g_sample_proto_constants;

} // namespace

#endif
